use soroban_sdk::{Address, contracttype};

#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum CampaignStatus {
    Active,
    Completed,
    Suspended,
    Rejected,
}

/// Wrapper for an optional token contract address.
///
/// `Option<Address>` cannot be used as a `#[contracttype]` struct field in
/// soroban-sdk 20.5.0 because there is no `TryFrom<&Option<Address>> for ScVal`
/// blanket impl. This enum is the idiomatic Soroban workaround and gets its
/// `TryFrom`/`FromVal`/`IntoVal` impls autogenerated by the `#[contracttype]`
/// derive. With `testutils` feature enabled on `soroban-sdk`, the macro also
/// generates the `SorobanArbitrary` trait impl needed for cross-version-stable
/// test fixtures.
#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum AssetContract {
    None,
    Some(Address),
}

impl AssetContract {
    /// Construct from a Rust `Option<Address>`.
    pub fn from_opt(opt: Option<Address>) -> Self {
        match opt {
            Some(addr) => AssetContract::Some(addr),
            None => AssetContract::None,
        }
    }

    /// Convert back into a Rust `Option<Address>`.
    pub fn into_opt(self) -> Option<Address> {
        match self {
            AssetContract::Some(addr) => Some(addr),
            AssetContract::None => None,
        }
    }
}

#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Campaign {
    pub id: u64,
    pub owner: Address,
    pub goal: i128,
    pub raised: i128,
    pub status: CampaignStatus,
    pub deadline: u64,
    pub asset_contract_id: AssetContract,
}

#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Donation {
    pub donor: Address,
    pub campaign_id: u64,
    pub amount: i128,
    pub timestamp: u64,
}

#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Withdrawal {
    pub campaign_id: u64,
    pub recipient: Address,
    pub amount: i128,
    pub approved: bool,
}
